### ISSUE TITLE
python setup.py egg_info" failed with error code 1 in django-tracking

### ISSUE THREAD

**Issue by seenureddy** [bashu/django-tracking#22]
I'm tying to install the django-tracking repository as follows in my `requirements.txt`

-e git+https://github.com/bashu/django-tracking@092c42a36137b97be364299f3746fdf68f6df6a0#egg=django-tracking
I'm getting the following error I have no idea how to solve this

Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "/Users/user_name/venvs/project/src/django-tracking/setup.py", line 6, in <module>
          import tracking
          File "tracking/**init**.py", line 1, in <module>
          import listeners
          File "tracking/listeners.py", line 6, in <module>
          from django.core.cache import cache
          File "/Users/user_name/venvs/project/lib/python2.7/site-packages/django/core/cache/**init**.py", line 34, in <module>
          if DEFAULT_CACHE_ALIAS not in settings.CACHES:
              File "/Users/user_name/venvs/project/lib/python2.7/site-packages/django/conf/**init**.py", line 46, in **getattr**
             self._setup(name)
          File "/Users/user_name/venvs/project/lib/python2.7/site-packages/django/conf/__init__.py", line 40, in _setup
           % (desc, ENVIRONMENT_VARIABLE))
         django.core.exceptions.ImproperlyConfigured: Requested setting CACHES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /Users/user/venvs/project/src/django-tracking

**Comment by ankitgoyalgithub** [comment]
Getting ImportError: No module named 'listeners' while installing this module and also couldn't find any such module listeners which satisfies the requirement

**Comment by arthurfaccioly** [comment]
Same here. Did you find a solution?

**Comment by johnsliao** [comment]
`pip install git+https://github.com/bashu/django-tracking.git`
