### ISSUE TITLE
ImportError: No module named 'listeners'

### ISSUE THREAD

**Issue by ShivaGuntuku** [bashu/django-tracking#26]
Collecting django-tracking
  Using cached django-tracking-0.4.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\gshiv\AppData\Local\Temp\pip-build-odmfikyz\django-tracking\setup.py", line 6, in <module>
        import tracking
      File "c:\users\gshiv\appdata\local\temp\pip-build-odmfikyz\django-tracking\tracking__init__.py", line 1, in <module>
        import listeners
    ImportError: No module named 'listeners'

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in C:\Users\gshiv\AppData\Local\Temp\pip-build-odmfikyz\django-tracking\

i did n't find any module listeners. help me how to get rid up this problem.

**Comment by arpit1997** [comment]
I got the same issue @ShivaGuntuku 

> Collecting django-tracking
>   Downloading django-tracking-0.4.1.tar.gz (1.9MB)
>     100% |████████████████████████████████| 1.9MB 319kB/s 
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-kouqjcaa/django-tracking/setup.py", line 6, in <module>
>         import tracking
>       File "/tmp/pip-build-kouqjcaa/django-tracking/tracking/**init**.py", line 1, in <module>
>         import listeners
>     ImportError: No module named 'listeners'

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kouqjcaa/django-tracking/
Anyone found any answer to this.
@bashu

**Comment by williamd1k0** [comment]
This is an issue with pypi version of django-tracking.
Try downloading the develop branch and installing from source:

```bash
python setup.py install
```

**Comment by johnsliao** [comment]
This worked: `pip install git+https://github.com/bashu/django-tracking.git`

**Comment by daviwesley** [comment]
@johnsliao for me too!!

**Comment by pylixm** [comment]
@johnsliao  good job !!!

**Comment by stselvam** [comment]
@johnsliao Worked for me too

**Comment by mkornyev** [comment]
Running 
`pip install git+https://github.com/bashu/django-tracking.git`
then 
`python manage.py syncdb`
worked for me.

**Comment by giuseppericci** [comment]
I have the same error and the proposed solutions form me they doesn't work. Please you can help me?
I'm in a venv based on Python 3.8.16 and django 4.1.7.
